---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: myApp.dev
    timezone: UTC
  vars_files:
    - vars/app.yml
    - ansible-playbook/ansible/vars/yo.yml
    - ansible-playbook/ansible/vars/mysql.yml
    - ansible-playbook/ansible/vars/pgsql.yml
    - ansible-playbook/ansible/vars/common.yml
    - ansible-playbook/ansible/vars/nginxphp.yml
    - ansible-playbook/ansible/vars/ws_defaults.yml
    - ansible-playbook/ansible/vars/mongodb.yml
  roles:
    - ../ansible-playbook/ansible/roles/init
    - ../ansible-playbook/ansible/roles/nginx
    - ../ansible-playbook/ansible/roles/java
    - ../ansible-playbook/ansible/roles/solr
    # - elasticsearch
    - ../ansible-playbook/ansible/roles/php5-cli
    - ../ansible-playbook/ansible/roles/php5-fpm
    - ../ansible-playbook/ansible/roles/phpcommon
    - ../ansible-playbook/ansible/roles/php-pecl
    - ../ansible-playbook/ansible/roles/nodejs
    # - mongodb
    - ../ansible-playbook/ansible/roles/composer
    # - mysql
    # - pgsql
    - ../ansible-playbook/ansible/roles/app
    # - yo
